go_library(
  name='lib',
  srcs=glob(['*.go'], exclude=['*_test.go']),
  visibility=['PUBLIC'],
  tests=[':all_tests', ':copied_test'],
  deps=[
    '//vendor/gopkg.in/yaml.v2:lib'
  ]
)

go_test(
  name='all_tests',
  library=':lib',
  srcs=['unmarshall_test.go'],
  deps=[
    '//vendor/gopkg.in/yaml.v2:lib'
  ]
)
