go_library(
  name='lib',
  srcs=glob(['*.go'], excludes=['*_test.go']),
  visibility=['PUBLIC'],
  tests=[':unmarshall_test'],
  deps=[
    '//vendor/gopkg.in/yaml.v2:lib'
  ]
)

go_test(
  name='unmarshall_test',
  library=':lib',
  srcs=['unmarshall_test.go'],
  deps=[
    '//vendor/gopkg.in/yaml.v2:lib'
  ]
)