go_binary(
    name='bin',
    srcs=['main.go'],
    deps=[':cgo'],
)

cgo_library(
    name='cgo',
    package_name='cgo',
    header_namespace = "",
    headers = ['call_go.h'],
    srcs=['export-to-c.go',
        'call_go.c', 'cgosrc.go']
)